services:
  loki:
    image: grafana/loki:3.0.0                           # Specifies the Loki Docker image and version.
    container_name: loki                                # Names the container for easier management.
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml # Mounts the Loki configuration file.
    ports:
      - "3100:3100"                                     # Maps port 3100 on the host to port 3100 in the container.
    command: -config.file=/mnt/config/loki-config.yaml  # Runs Loki with the specified configuration file.

  jaegerLe:
    image: ghcr.io/asadarafat/jaegerle:v0.0.3            # Specifies the jaegerLe Docker image and version.
    container_name: jaegerLe                             # Names the container for easier management.
    volumes:
      - /var/jaegerle-config.yaml:/opt/jaegerLe/config/jaegerle-config.yaml          # Mounts the jaegerLe configuration file.
    depends_on:
      - loki                                                       # Ensures jaegerLe starts after Loki.
    command: ./jaegerLe --config /opt/jaegerLe/config/jaegerle-config.yaml    # Runs jaegerLe with the specified configuration file.