name: Build, Deploy, and Docker Image CI

on: 
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch all tags
      run: git fetch --tags

    - name: Extract the latest tag
      id: extract_tag
      run: |
        TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "TAG=${TAG}" >> $GITHUB_ENV

    - name: Display Tag Name
      run: echo "Tag=${{ env.TAG }}"

    - name: Change ownership of files (if necessary)
      run: sudo chown -R $USER:$USER *

    - name: List files in go_jaegerle directory
      run: ls -al go_jaegerle

    - name: Backup constants.go
      run: cp go_jaegerle/constants.go go_jaegerle/constants.go.bak

    - name: Update version in constants.go
      run: |
        sed -i "s/\(var VersionInfo string = \)\"[^\"]*\"/\1\"${{ env.TAG }}\"/" go_jaegerle/constants.go

    - name: Clean up dist folder
      run: |
        rm -rf dist/*
        mkdir -p dist

    - name: Build Linux Binary
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o jaegerLe ./go_jaegerle/cmd

    - name: Verify Build
      run: if [ ! -f jaegerLe ]; then echo "Build failed" && exit 1; fi

    - name: Move and Copy Files to dist
      run: |
        mv jaegerLe dist/jaegerLe
        cp -r config dist

    - name: Upload Distribution Build as an Artifact
      uses: actions/upload-artifact@v3
      with:
        name: jaegerLe
        path: dist/

  docker:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        labels: |
          org.opencontainers.image.created=${{ steps.meta.outputs.created }}
          org.opencontainers.image.version=${{ env.TAG }}
          org.opencontainers.image.revision=${{ github.sha }}
