name: Build, Deploy, and Docker Image CI

on: 
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: asadarafat/jaegerLe

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch all tags
      run: git fetch --tags

    - name: Extract the latest tag
      id: extract_tag
      run: |
        TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "TAG=${TAG}" >> $GITHUB_ENV

    - name: Display Tag Name
      run: echo "Tag=${{ env.TAG }}"

    - name: Change ownership of files (if necessary)
      run: sudo chown -R $USER:$USER *

    - name: List files in go_jaegerle directory
      run: ls -al go_jaegerle

    - name: Backup constants.go
      run: cp go_jaegerle/constants.go go_jaegerle/constants.go.bak

    - name: Update version in constants.go
      run: |
        sed -i "s/\(var VersionInfo string = \)\"[^\"]*\"/\1\"${{ env.TAG }}\"/" go_jaegerle/constants.go

    - name: Clean up dist folder
      run: |
        rm -rf dist/*
        mkdir -p dist

    - name: Build Linux Binary
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o jaegerLe ./go_jaegerle/cmd

    - name: Verify Build
      run: if [ ! -f jaegerLe ]; then echo "Build failed" && exit 1; fi

    - name: Move and Copy Files to dist
      run: |
        mv jaegerLe dist/jaegerLe
        cp -r config dist

    - name: Upload Distribution Build as an Artifact
      uses: actions/upload-artifact@v3
      with:
        name: jaegerLe
        path: dist/

  docker:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}


  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract the latest tag
      id: extract_tag
      run: |
        TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "TAG=${TAG}" >> $GITHUB_ENV

    - name: Display Tag Name
      run: echo "Tag=${{ env.TAG }}"
    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.TAG }}
        release_name: Release ${{ env.TAG }}
        body: |
          ## Changes
          - Description of changes for release ${{ env.TAG }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Build Artifact to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/jaegerLe
        asset_name: jaegerLe
        asset_content_type: application/octet-stream
