name: Build and Deploy

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Display Tag Name
      run: echo "Tag=${{ github.event.inputs.tag }}"

    - name: Change ownership of files (if necessary)
      run: sudo chown -R $USER:$USER *

    - name: List files in go_jaegerle directory
      run: ls -al go_jaegerle

    - name: Backup constants.go
      run: cp go_jaegerle/constants.go go_jaegerle/constants.go.bak

    - name: Update version in constants.go
      run: |
        sed -i "s/\(var VersionInfo string = \)\"[^\"]*\"/\1\"${{ github.event.inputs.tag }}\"/" go_jaegerle/constants.go

    - name: Clean up dist folder
      run: |
        rm -rf dist/*
        mkdir -p dist

    - name: Build Linux Binary
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o jaegerLe ./go_jaegerle/cmd

    - name: Verify Build
      run: if [ ! -f jaegerLe ]; then echo "Build failed" && exit 1; fi

    - name: Move and Copy Files to dist
      run: |
        mv jaegerLe dist/jaegerLe
        cp -r config dist

    - name: Upload Distribution Build as an Artifact
      uses: actions/upload-artifact@v3
      with:
        name: jaegerLe
        path: dist/
